### ISSUE TITLE
No module named 'deep_model'

### ISSUE THREAD

**Issue by Shuaibiqbal4603** [Eligijus112/deep-learning-ts#4]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-395213f79207> in <module>
     11 
     12 # The deep learning class
---> 13 from deep_model import DeepModel
     14 
     15 # Reading the configuration file

ModuleNotFoundError: No module named 'deep_model'

how can we set this error

**Comment by Eligijus112** [comment]
Hey, the line in pipeline.py in the main branch is from depp_model import DeepModelTS. Is there still an issue?
